<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda Online</title>
</head>
<body>
    <h1>Tienda Online</h1>
    <?php
        if(empty($_SESSION['user'])){
            echo '
            <form action="index.php?c=user" method="POST"><br>
            <input type="text" name="name" placeholder="Nombre" required><br><br>
            <input type="password" name="password" placeholder="Contraseña" required><br><br>
            <input type="submit" name="login" value="Iniciar sesión">';
        }
    ?>
</form><br>
    <?php
        if(!empty($_SESSION['user'])){
            echo $_SESSION['user']->__toString().".<br>";
        }
        if(!empty($_SESSION['user']) && $_SESSION['user']->getRol()>=2){
            echo "<a href='index.php?c=product&newProduct=1'>Añadír nuevo producto a la tienda.</a><br>";
            echo "<a href='index.php?c=admin&admin=1'>Administración.</a><br>";
        }
        if(!empty($_SESSION['user']) && $_SESSION['user']->getRol()>0){
            echo "<a href='index.php?c=pedido&registro=1'>Revisa tus compras.</a><br>";
            echo "<a href='index.php?c=pedido&compra=1'>Revisar/realizar compra.</a><br>";
            echo "<a href='index.php?c=user&logout=1'>Cerrar sesión.</a>";
        }

        echo '<br>';
        echo '<br>';
        echo '<h2>Lista de artículos</h2>';
        echo '<br>';
        foreach($products as $product){
            echo '<div style="background-color: #ccc; width:40%; margin-bottom:20px; padding: 10px; padding-left:30px; border-radius:25px;">';
            echo '<h3>'.$product->getName().'</h3>';
            echo '<p>'.$product->getDescription().'</p>';
            echo "<img src='public/img/".$product->getImage()."' width='300px'/>";
            echo '<p style="font-size:20px;">'.$product->getPrice().'€</p>';
            if(!empty($_SESSION['user']) && $_SESSION['user']->getRol()>=1){
                echo '<a href="index.php?c=product&product='.$product->getId().'">Ver más</a>';
            }
            echo '<br><br><br>';
            echo '</div>';
        }

    ?>
</body>
</html>