<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Playlist - Reproductor de Música</title>
    <!-- Agregamos Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #0e0e10;
            /* Fondo oscuro similar a Spotify */
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            color: #fff;
            /* Texto blanco */
        }

        h1,
        h2,
        h3,
        h4 {
            color: #fff;
            /* Letras en blanco */
        }

        a {
            text-decoration: none;
            color: #1db954;
            /* Verde brillante similar a Spotify */
        }

        a:hover {
            text-decoration: underline;
        }

        form {
            max-width: 400px;
            margin: auto;
        }

        input,
        select {
            width: 100%;
            padding: 8px;
            margin-bottom: 12px;
            border: 1px solid #535353;
            /* Gris oscuro similar a Spotify */
            border-radius: 4px;
            background-color: #121212;
            /* Fondo oscuro similar a Spotify */
            color: #fff;
            /* Texto blanco */
        }

        input[type="submit"] {
            background-color: #1db954;
            /* Verde brillante similar a Spotify */
            color: #fff;
            /* Texto blanco */
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #25a056;
            /* Verde ligeramente más oscuro al pasar el mouse */
        }
    </style>
</head>

<body class="mx-auto max-w-screen-2xl p-4">
</body>



<?php
echo "<a href='index.php' class='text-blue-500'>Volver</a>";
echo '<form method="POST" action="index.php?c=createList" enctype="multipart/form-data" class="mb-4">
            <input type="text" name="tNPlay" placeholder="Nombre de playlist" class="mb-4 p-2 border border-gray-300"/>
            <input type="file" name="img" required class="mb-4 p-2 border border-gray-300"/>
            <input type="submit" name="create" value="Crear" class="p-2 bg-blue-500 text-white"/>
        </form>';
?>

</body>

</html>